name: nvidia-smi 
base: core24 
version: '0.1' 
summary: NVIDIA System Management Interface SMI 
description: |
  The NVIDIA System Management Interface (nvidia-smi) is a command line utility, based on top of the NVIDIA Management Library (NVML), intended to aid in the management and monitoring of NVIDIA GPU devices.

grade: devel 
confinement: devmode 

apps:
  nvidia-smi:
    command: usr/bin/nvidia-smi

parts:
  nvidia-smi:
    plugin: nil
    stage-packages:
      - nvidia-driver-550-server

